package types

// ImplementationPlan represents the plan generated by AI
type ImplementationPlan struct {
	Summary             string
	Steps               []PlanStep
	FilesToModify       []string
	FilesToCreate       []string
	EstimatedComplexity string
}

// PlanStep represents a single step in the implementation plan
type PlanStep struct {
	Order        int
	Description  string
	ActivityType string // codegen, testing, deployment, review
	Parameters   map[string]string
}
