// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/leader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartWorkflowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JiraTicketId    string                 `protobuf:"bytes,1,opt,name=jira_ticket_id,json=jiraTicketId,proto3" json:"jira_ticket_id,omitempty"`
	RepositoryOwner string                 `protobuf:"bytes,2,opt,name=repository_owner,json=repositoryOwner,proto3" json:"repository_owner,omitempty"`
	RepositoryName  string                 `protobuf:"bytes,3,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	BaseBranch      string                 `protobuf:"bytes,4,opt,name=base_branch,json=baseBranch,proto3" json:"base_branch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_proto_leader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{0}
}

func (x *StartWorkflowRequest) GetJiraTicketId() string {
	if x != nil {
		return x.JiraTicketId
	}
	return ""
}

func (x *StartWorkflowRequest) GetRepositoryOwner() string {
	if x != nil {
		return x.RepositoryOwner
	}
	return ""
}

func (x *StartWorkflowRequest) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *StartWorkflowRequest) GetBaseBranch() string {
	if x != nil {
		return x.BaseBranch
	}
	return ""
}

type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_proto_leader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{1}
}

func (x *StartWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetWorkflowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusRequest) Reset() {
	*x = GetWorkflowStatusRequest{}
	mi := &file_proto_leader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusRequest) ProtoMessage() {}

func (x *GetWorkflowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkflowStatusRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	JiraTicketId  string                 `protobuf:"bytes,3,opt,name=jira_ticket_id,json=jiraTicketId,proto3" json:"jira_ticket_id,omitempty"`
	PrUrl         string                 `protobuf:"bytes,4,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusResponse) Reset() {
	*x = GetWorkflowStatusResponse{}
	mi := &file_proto_leader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusResponse) ProtoMessage() {}

func (x *GetWorkflowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkflowStatusResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetWorkflowStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetWorkflowStatusResponse) GetJiraTicketId() string {
	if x != nil {
		return x.JiraTicketId
	}
	return ""
}

func (x *GetWorkflowStatusResponse) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *GetWorkflowStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CancelWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_proto_leader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{4}
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type CancelWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_proto_leader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{5}
}

func (x *CancelWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelWorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProcessedTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessedTasksRequest) Reset() {
	*x = GetProcessedTasksRequest{}
	mi := &file_proto_leader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessedTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessedTasksRequest) ProtoMessage() {}

func (x *GetProcessedTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessedTasksRequest.ProtoReflect.Descriptor instead.
func (*GetProcessedTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{6}
}

func (x *GetProcessedTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProcessedTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ProcessedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JiraTicketId  string                 `protobuf:"bytes,1,opt,name=jira_ticket_id,json=jiraTicketId,proto3" json:"jira_ticket_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedTask) Reset() {
	*x = ProcessedTask{}
	mi := &file_proto_leader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTask) ProtoMessage() {}

func (x *ProcessedTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTask.ProtoReflect.Descriptor instead.
func (*ProcessedTask) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessedTask) GetJiraTicketId() string {
	if x != nil {
		return x.JiraTicketId
	}
	return ""
}

func (x *ProcessedTask) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ProcessedTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessedTask) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetProcessedTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*ProcessedTask       `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessedTasksResponse) Reset() {
	*x = GetProcessedTasksResponse{}
	mi := &file_proto_leader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessedTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessedTasksResponse) ProtoMessage() {}

func (x *GetProcessedTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessedTasksResponse.ProtoReflect.Descriptor instead.
func (*GetProcessedTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_leader_proto_rawDescGZIP(), []int{8}
}

func (x *GetProcessedTasksResponse) GetTasks() []*ProcessedTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetProcessedTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_leader_proto protoreflect.FileDescriptor

const file_proto_leader_proto_rawDesc = "" +
	"\n" +
	"\x12proto/leader.proto\x12\x06leader\"\xb1\x01\n" +
	"\x14StartWorkflowRequest\x12$\n" +
	"\x0ejira_ticket_id\x18\x01 \x01(\tR\fjiraTicketId\x12)\n" +
	"\x10repository_owner\x18\x02 \x01(\tR\x0frepositoryOwner\x12'\n" +
	"\x0frepository_name\x18\x03 \x01(\tR\x0erepositoryName\x12\x1f\n" +
	"\vbase_branch\x18\x04 \x01(\tR\n" +
	"baseBranch\"P\n" +
	"\x15StartWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\";\n" +
	"\x18GetWorkflowStatusRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\xb6\x01\n" +
	"\x19GetWorkflowStatusResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\x0ejira_ticket_id\x18\x03 \x01(\tR\fjiraTicketId\x12\x15\n" +
	"\x06pr_url\x18\x04 \x01(\tR\x05prUrl\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"8\n" +
	"\x15CancelWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"L\n" +
	"\x16CancelWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x18GetProcessedTasksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x8d\x01\n" +
	"\rProcessedTask\x12$\n" +
	"\x0ejira_ticket_id\x18\x01 \x01(\tR\fjiraTicketId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"^\n" +
	"\x19GetProcessedTasksResponse\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.leader.ProcessedTaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xe2\x02\n" +
	"\rLeaderService\x12L\n" +
	"\rStartWorkflow\x12\x1c.leader.StartWorkflowRequest\x1a\x1d.leader.StartWorkflowResponse\x12X\n" +
	"\x11GetWorkflowStatus\x12 .leader.GetWorkflowStatusRequest\x1a!.leader.GetWorkflowStatusResponse\x12O\n" +
	"\x0eCancelWorkflow\x12\x1d.leader.CancelWorkflowRequest\x1a\x1e.leader.CancelWorkflowResponse\x12X\n" +
	"\x11GetProcessedTasks\x12 .leader.GetProcessedTasksRequest\x1a!.leader.GetProcessedTasksResponseB'Z%github.com/clintrovert/khitomer/protob\x06proto3"

var (
	file_proto_leader_proto_rawDescOnce sync.Once
	file_proto_leader_proto_rawDescData []byte
)

func file_proto_leader_proto_rawDescGZIP() []byte {
	file_proto_leader_proto_rawDescOnce.Do(func() {
		file_proto_leader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_leader_proto_rawDesc), len(file_proto_leader_proto_rawDesc)))
	})
	return file_proto_leader_proto_rawDescData
}

var file_proto_leader_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_leader_proto_goTypes = []any{
	(*StartWorkflowRequest)(nil),      // 0: leader.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),     // 1: leader.StartWorkflowResponse
	(*GetWorkflowStatusRequest)(nil),  // 2: leader.GetWorkflowStatusRequest
	(*GetWorkflowStatusResponse)(nil), // 3: leader.GetWorkflowStatusResponse
	(*CancelWorkflowRequest)(nil),     // 4: leader.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil),    // 5: leader.CancelWorkflowResponse
	(*GetProcessedTasksRequest)(nil),  // 6: leader.GetProcessedTasksRequest
	(*ProcessedTask)(nil),             // 7: leader.ProcessedTask
	(*GetProcessedTasksResponse)(nil), // 8: leader.GetProcessedTasksResponse
}
var file_proto_leader_proto_depIdxs = []int32{
	7, // 0: leader.GetProcessedTasksResponse.tasks:type_name -> leader.ProcessedTask
	0, // 1: leader.LeaderService.StartWorkflow:input_type -> leader.StartWorkflowRequest
	2, // 2: leader.LeaderService.GetWorkflowStatus:input_type -> leader.GetWorkflowStatusRequest
	4, // 3: leader.LeaderService.CancelWorkflow:input_type -> leader.CancelWorkflowRequest
	6, // 4: leader.LeaderService.GetProcessedTasks:input_type -> leader.GetProcessedTasksRequest
	1, // 5: leader.LeaderService.StartWorkflow:output_type -> leader.StartWorkflowResponse
	3, // 6: leader.LeaderService.GetWorkflowStatus:output_type -> leader.GetWorkflowStatusResponse
	5, // 7: leader.LeaderService.CancelWorkflow:output_type -> leader.CancelWorkflowResponse
	8, // 8: leader.LeaderService.GetProcessedTasks:output_type -> leader.GetProcessedTasksResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_leader_proto_init() }
func file_proto_leader_proto_init() {
	if File_proto_leader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_leader_proto_rawDesc), len(file_proto_leader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_leader_proto_goTypes,
		DependencyIndexes: file_proto_leader_proto_depIdxs,
		MessageInfos:      file_proto_leader_proto_msgTypes,
	}.Build()
	File_proto_leader_proto = out.File
	file_proto_leader_proto_goTypes = nil
	file_proto_leader_proto_depIdxs = nil
}
