// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/workflows.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task metadata from Jira
type TaskMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JiraTicketId    string                 `protobuf:"bytes,1,opt,name=jira_ticket_id,json=jiraTicketId,proto3" json:"jira_ticket_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Assignee        string                 `protobuf:"bytes,5,opt,name=assignee,proto3" json:"assignee,omitempty"`
	RepositoryOwner string                 `protobuf:"bytes,6,opt,name=repository_owner,json=repositoryOwner,proto3" json:"repository_owner,omitempty"`
	RepositoryName  string                 `protobuf:"bytes,7,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	RepositoryUrl   string                 `protobuf:"bytes,8,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	BaseBranch      string                 `protobuf:"bytes,9,opt,name=base_branch,json=baseBranch,proto3" json:"base_branch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskMetadata) Reset() {
	*x = TaskMetadata{}
	mi := &file_proto_workflows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMetadata) ProtoMessage() {}

func (x *TaskMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMetadata.ProtoReflect.Descriptor instead.
func (*TaskMetadata) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{0}
}

func (x *TaskMetadata) GetJiraTicketId() string {
	if x != nil {
		return x.JiraTicketId
	}
	return ""
}

func (x *TaskMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskMetadata) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *TaskMetadata) GetRepositoryOwner() string {
	if x != nil {
		return x.RepositoryOwner
	}
	return ""
}

func (x *TaskMetadata) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *TaskMetadata) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *TaskMetadata) GetBaseBranch() string {
	if x != nil {
		return x.BaseBranch
	}
	return ""
}

// Implementation plan generated by AI
type ImplementationPlan struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Summary             string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Steps               []*PlanStep            `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	FilesToModify       []string               `protobuf:"bytes,3,rep,name=files_to_modify,json=filesToModify,proto3" json:"files_to_modify,omitempty"`
	FilesToCreate       []string               `protobuf:"bytes,4,rep,name=files_to_create,json=filesToCreate,proto3" json:"files_to_create,omitempty"`
	EstimatedComplexity string                 `protobuf:"bytes,5,opt,name=estimated_complexity,json=estimatedComplexity,proto3" json:"estimated_complexity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ImplementationPlan) Reset() {
	*x = ImplementationPlan{}
	mi := &file_proto_workflows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementationPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementationPlan) ProtoMessage() {}

func (x *ImplementationPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementationPlan.ProtoReflect.Descriptor instead.
func (*ImplementationPlan) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{1}
}

func (x *ImplementationPlan) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ImplementationPlan) GetSteps() []*PlanStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ImplementationPlan) GetFilesToModify() []string {
	if x != nil {
		return x.FilesToModify
	}
	return nil
}

func (x *ImplementationPlan) GetFilesToCreate() []string {
	if x != nil {
		return x.FilesToCreate
	}
	return nil
}

func (x *ImplementationPlan) GetEstimatedComplexity() string {
	if x != nil {
		return x.EstimatedComplexity
	}
	return ""
}

type PlanStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         int32                  `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ActivityType  string                 `protobuf:"bytes,3,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"` // codegen, testing, deployment, review
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanStep) Reset() {
	*x = PlanStep{}
	mi := &file_proto_workflows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanStep) ProtoMessage() {}

func (x *PlanStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanStep.ProtoReflect.Descriptor instead.
func (*PlanStep) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{2}
}

func (x *PlanStep) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *PlanStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlanStep) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *PlanStep) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// GitHub repository information
type RepositoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseBranch    string                 `protobuf:"bytes,3,opt,name=base_branch,json=baseBranch,proto3" json:"base_branch,omitempty"`
	FeatureBranch string                 `protobuf:"bytes,4,opt,name=feature_branch,json=featureBranch,proto3" json:"feature_branch,omitempty"`
	CloneUrl      string                 `protobuf:"bytes,5,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryInfo) Reset() {
	*x = RepositoryInfo{}
	mi := &file_proto_workflows_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryInfo) ProtoMessage() {}

func (x *RepositoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryInfo.ProtoReflect.Descriptor instead.
func (*RepositoryInfo) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{3}
}

func (x *RepositoryInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepositoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepositoryInfo) GetBaseBranch() string {
	if x != nil {
		return x.BaseBranch
	}
	return ""
}

func (x *RepositoryInfo) GetFeatureBranch() string {
	if x != nil {
		return x.FeatureBranch
	}
	return ""
}

func (x *RepositoryInfo) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

// PR information
type PRInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrNumber      int64                  `protobuf:"varint,1,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	PrUrl         string                 `protobuf:"bytes,2,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PRInfo) Reset() {
	*x = PRInfo{}
	mi := &file_proto_workflows_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PRInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRInfo) ProtoMessage() {}

func (x *PRInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRInfo.ProtoReflect.Descriptor instead.
func (*PRInfo) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{4}
}

func (x *PRInfo) GetPrNumber() int64 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

func (x *PRInfo) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *PRInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PRInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PRInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Workflow input
type WorkflowInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskMetadata          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Plan          *ImplementationPlan    `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Repository    *RepositoryInfo        `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInput) Reset() {
	*x = WorkflowInput{}
	mi := &file_proto_workflows_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInput) ProtoMessage() {}

func (x *WorkflowInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInput.ProtoReflect.Descriptor instead.
func (*WorkflowInput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowInput) GetTask() *TaskMetadata {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *WorkflowInput) GetPlan() *ImplementationPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *WorkflowInput) GetRepository() *RepositoryInfo {
	if x != nil {
		return x.Repository
	}
	return nil
}

// Activity inputs/outputs
type CodeGenerationInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	Plan           *ImplementationPlan    `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Task           *TaskMetadata          `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodeGenerationInput) Reset() {
	*x = CodeGenerationInput{}
	mi := &file_proto_workflows_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeGenerationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeGenerationInput) ProtoMessage() {}

func (x *CodeGenerationInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeGenerationInput.ProtoReflect.Descriptor instead.
func (*CodeGenerationInput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{6}
}

func (x *CodeGenerationInput) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *CodeGenerationInput) GetPlan() *ImplementationPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *CodeGenerationInput) GetTask() *TaskMetadata {
	if x != nil {
		return x.Task
	}
	return nil
}

type CodeGenerationOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModifiedFiles []string               `protobuf:"bytes,1,rep,name=modified_files,json=modifiedFiles,proto3" json:"modified_files,omitempty"`
	CreatedFiles  []string               `protobuf:"bytes,2,rep,name=created_files,json=createdFiles,proto3" json:"created_files,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeGenerationOutput) Reset() {
	*x = CodeGenerationOutput{}
	mi := &file_proto_workflows_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeGenerationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeGenerationOutput) ProtoMessage() {}

func (x *CodeGenerationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeGenerationOutput.ProtoReflect.Descriptor instead.
func (*CodeGenerationOutput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{7}
}

func (x *CodeGenerationOutput) GetModifiedFiles() []string {
	if x != nil {
		return x.ModifiedFiles
	}
	return nil
}

func (x *CodeGenerationOutput) GetCreatedFiles() []string {
	if x != nil {
		return x.CreatedFiles
	}
	return nil
}

func (x *CodeGenerationOutput) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type TestingInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	TestFiles      []string               `protobuf:"bytes,2,rep,name=test_files,json=testFiles,proto3" json:"test_files,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestingInput) Reset() {
	*x = TestingInput{}
	mi := &file_proto_workflows_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingInput) ProtoMessage() {}

func (x *TestingInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingInput.ProtoReflect.Descriptor instead.
func (*TestingInput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{8}
}

func (x *TestingInput) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *TestingInput) GetTestFiles() []string {
	if x != nil {
		return x.TestFiles
	}
	return nil
}

type TestingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Failures      []string               `protobuf:"bytes,3,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestingOutput) Reset() {
	*x = TestingOutput{}
	mi := &file_proto_workflows_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingOutput) ProtoMessage() {}

func (x *TestingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingOutput.ProtoReflect.Descriptor instead.
func (*TestingOutput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{9}
}

func (x *TestingOutput) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestingOutput) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TestingOutput) GetFailures() []string {
	if x != nil {
		return x.Failures
	}
	return nil
}

type GitHubOperationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *RepositoryInfo        `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // clone, branch, commit, pr
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubOperationInput) Reset() {
	*x = GitHubOperationInput{}
	mi := &file_proto_workflows_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubOperationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubOperationInput) ProtoMessage() {}

func (x *GitHubOperationInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubOperationInput.ProtoReflect.Descriptor instead.
func (*GitHubOperationInput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{10}
}

func (x *GitHubOperationInput) GetRepository() *RepositoryInfo {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *GitHubOperationInput) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *GitHubOperationInput) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GitHubOperationOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PrInfo        *PRInfo                `protobuf:"bytes,3,opt,name=pr_info,json=prInfo,proto3" json:"pr_info,omitempty"`
	BranchName    string                 `protobuf:"bytes,4,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubOperationOutput) Reset() {
	*x = GitHubOperationOutput{}
	mi := &file_proto_workflows_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubOperationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubOperationOutput) ProtoMessage() {}

func (x *GitHubOperationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubOperationOutput.ProtoReflect.Descriptor instead.
func (*GitHubOperationOutput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{11}
}

func (x *GitHubOperationOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GitHubOperationOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GitHubOperationOutput) GetPrInfo() *PRInfo {
	if x != nil {
		return x.PrInfo
	}
	return nil
}

func (x *GitHubOperationOutput) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

type JiraUpdateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	PrUrl         string                 `protobuf:"bytes,4,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	Attachments   []string               `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JiraUpdateInput) Reset() {
	*x = JiraUpdateInput{}
	mi := &file_proto_workflows_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JiraUpdateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JiraUpdateInput) ProtoMessage() {}

func (x *JiraUpdateInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JiraUpdateInput.ProtoReflect.Descriptor instead.
func (*JiraUpdateInput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{12}
}

func (x *JiraUpdateInput) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *JiraUpdateInput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JiraUpdateInput) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *JiraUpdateInput) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *JiraUpdateInput) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type JiraUpdateOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JiraUpdateOutput) Reset() {
	*x = JiraUpdateOutput{}
	mi := &file_proto_workflows_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JiraUpdateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JiraUpdateOutput) ProtoMessage() {}

func (x *JiraUpdateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflows_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JiraUpdateOutput.ProtoReflect.Descriptor instead.
func (*JiraUpdateOutput) Descriptor() ([]byte, []int) {
	return file_proto_workflows_proto_rawDescGZIP(), []int{13}
}

func (x *JiraUpdateOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JiraUpdateOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_workflows_proto protoreflect.FileDescriptor

const file_proto_workflows_proto_rawDesc = "" +
	"\n" +
	"\x15proto/workflows.proto\x12\tworkflows\"\xbc\x02\n" +
	"\fTaskMetadata\x12$\n" +
	"\x0ejira_ticket_id\x18\x01 \x01(\tR\fjiraTicketId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bassignee\x18\x05 \x01(\tR\bassignee\x12)\n" +
	"\x10repository_owner\x18\x06 \x01(\tR\x0frepositoryOwner\x12'\n" +
	"\x0frepository_name\x18\a \x01(\tR\x0erepositoryName\x12%\n" +
	"\x0erepository_url\x18\b \x01(\tR\rrepositoryUrl\x12\x1f\n" +
	"\vbase_branch\x18\t \x01(\tR\n" +
	"baseBranch\"\xdc\x01\n" +
	"\x12ImplementationPlan\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12)\n" +
	"\x05steps\x18\x02 \x03(\v2\x13.workflows.PlanStepR\x05steps\x12&\n" +
	"\x0ffiles_to_modify\x18\x03 \x03(\tR\rfilesToModify\x12&\n" +
	"\x0ffiles_to_create\x18\x04 \x03(\tR\rfilesToCreate\x121\n" +
	"\x14estimated_complexity\x18\x05 \x01(\tR\x13estimatedComplexity\"\xeb\x01\n" +
	"\bPlanStep\x12\x14\n" +
	"\x05order\x18\x01 \x01(\x05R\x05order\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\ractivity_type\x18\x03 \x01(\tR\factivityType\x12C\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2#.workflows.PlanStep.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x0eRepositoryInfo\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vbase_branch\x18\x03 \x01(\tR\n" +
	"baseBranch\x12%\n" +
	"\x0efeature_branch\x18\x04 \x01(\tR\rfeatureBranch\x12\x1b\n" +
	"\tclone_url\x18\x05 \x01(\tR\bcloneUrl\"\x8c\x01\n" +
	"\x06PRInfo\x12\x1b\n" +
	"\tpr_number\x18\x01 \x01(\x03R\bprNumber\x12\x15\n" +
	"\x06pr_url\x18\x02 \x01(\tR\x05prUrl\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xaa\x01\n" +
	"\rWorkflowInput\x12+\n" +
	"\x04task\x18\x01 \x01(\v2\x17.workflows.TaskMetadataR\x04task\x121\n" +
	"\x04plan\x18\x02 \x01(\v2\x1d.workflows.ImplementationPlanR\x04plan\x129\n" +
	"\n" +
	"repository\x18\x03 \x01(\v2\x19.workflows.RepositoryInfoR\n" +
	"repository\"\x9e\x01\n" +
	"\x13CodeGenerationInput\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x121\n" +
	"\x04plan\x18\x02 \x01(\v2\x1d.workflows.ImplementationPlanR\x04plan\x12+\n" +
	"\x04task\x18\x03 \x01(\v2\x17.workflows.TaskMetadataR\x04task\"|\n" +
	"\x14CodeGenerationOutput\x12%\n" +
	"\x0emodified_files\x18\x01 \x03(\tR\rmodifiedFiles\x12#\n" +
	"\rcreated_files\x18\x02 \x03(\tR\fcreatedFiles\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"V\n" +
	"\fTestingInput\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x1d\n" +
	"\n" +
	"test_files\x18\x02 \x03(\tR\ttestFiles\"[\n" +
	"\rTestingOutput\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1a\n" +
	"\bfailures\x18\x03 \x03(\tR\bfailures\"\xff\x01\n" +
	"\x14GitHubOperationInput\x129\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x19.workflows.RepositoryInfoR\n" +
	"repository\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12O\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2/.workflows.GitHubOperationInput.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x15GitHubOperationOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\apr_info\x18\x03 \x01(\v2\x11.workflows.PRInfoR\x06prInfo\x12\x1f\n" +
	"\vbranch_name\x18\x04 \x01(\tR\n" +
	"branchName\"\x99\x01\n" +
	"\x0fJiraUpdateInput\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x15\n" +
	"\x06pr_url\x18\x04 \x01(\tR\x05prUrl\x12 \n" +
	"\vattachments\x18\x05 \x03(\tR\vattachments\"F\n" +
	"\x10JiraUpdateOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB'Z%github.com/clintrovert/khitomer/protob\x06proto3"

var (
	file_proto_workflows_proto_rawDescOnce sync.Once
	file_proto_workflows_proto_rawDescData []byte
)

func file_proto_workflows_proto_rawDescGZIP() []byte {
	file_proto_workflows_proto_rawDescOnce.Do(func() {
		file_proto_workflows_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workflows_proto_rawDesc), len(file_proto_workflows_proto_rawDesc)))
	})
	return file_proto_workflows_proto_rawDescData
}

var file_proto_workflows_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_workflows_proto_goTypes = []any{
	(*TaskMetadata)(nil),          // 0: workflows.TaskMetadata
	(*ImplementationPlan)(nil),    // 1: workflows.ImplementationPlan
	(*PlanStep)(nil),              // 2: workflows.PlanStep
	(*RepositoryInfo)(nil),        // 3: workflows.RepositoryInfo
	(*PRInfo)(nil),                // 4: workflows.PRInfo
	(*WorkflowInput)(nil),         // 5: workflows.WorkflowInput
	(*CodeGenerationInput)(nil),   // 6: workflows.CodeGenerationInput
	(*CodeGenerationOutput)(nil),  // 7: workflows.CodeGenerationOutput
	(*TestingInput)(nil),          // 8: workflows.TestingInput
	(*TestingOutput)(nil),         // 9: workflows.TestingOutput
	(*GitHubOperationInput)(nil),  // 10: workflows.GitHubOperationInput
	(*GitHubOperationOutput)(nil), // 11: workflows.GitHubOperationOutput
	(*JiraUpdateInput)(nil),       // 12: workflows.JiraUpdateInput
	(*JiraUpdateOutput)(nil),      // 13: workflows.JiraUpdateOutput
	nil,                           // 14: workflows.PlanStep.ParametersEntry
	nil,                           // 15: workflows.GitHubOperationInput.ParametersEntry
}
var file_proto_workflows_proto_depIdxs = []int32{
	2,  // 0: workflows.ImplementationPlan.steps:type_name -> workflows.PlanStep
	14, // 1: workflows.PlanStep.parameters:type_name -> workflows.PlanStep.ParametersEntry
	0,  // 2: workflows.WorkflowInput.task:type_name -> workflows.TaskMetadata
	1,  // 3: workflows.WorkflowInput.plan:type_name -> workflows.ImplementationPlan
	3,  // 4: workflows.WorkflowInput.repository:type_name -> workflows.RepositoryInfo
	1,  // 5: workflows.CodeGenerationInput.plan:type_name -> workflows.ImplementationPlan
	0,  // 6: workflows.CodeGenerationInput.task:type_name -> workflows.TaskMetadata
	3,  // 7: workflows.GitHubOperationInput.repository:type_name -> workflows.RepositoryInfo
	15, // 8: workflows.GitHubOperationInput.parameters:type_name -> workflows.GitHubOperationInput.ParametersEntry
	4,  // 9: workflows.GitHubOperationOutput.pr_info:type_name -> workflows.PRInfo
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_workflows_proto_init() }
func file_proto_workflows_proto_init() {
	if File_proto_workflows_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workflows_proto_rawDesc), len(file_proto_workflows_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_workflows_proto_goTypes,
		DependencyIndexes: file_proto_workflows_proto_depIdxs,
		MessageInfos:      file_proto_workflows_proto_msgTypes,
	}.Build()
	File_proto_workflows_proto = out.File
	file_proto_workflows_proto_goTypes = nil
	file_proto_workflows_proto_depIdxs = nil
}
